# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Repo Visualizer
      - name: Repo Visualizer
      # You may pin to the exact commit or the version.
      # uses: githubocto/repo-visualizer@d89437ae41087c95815abff164cc3d64b37f323a
        uses: githubocto/repo-visualizer@0.3.0
        with:
          # A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg
          output_file: diagram.svg
          # A list of paths to exclude from the diagram, separated by commas. For example: dist,node_modules
          excluded_paths: dist,node_modules
          # The maximum number of nested folders to show files within. Default: 9
          max_depth: 9
